# Generated by Django 3.1.4 on 2020-12-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsefacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='horsefact',
            table='horsefacts',
        ),
    ]
